### ISSUE TITLE
Error downloading Maps wallpapers: No JSON object could be decoded

### ISSUE THREAD

**Issue by kylrth** [ming13/google-wallpaper-downloaders#2]
Got this error running the code from master:
```
user@computer: google-wallpaper-downloaders$ python2 maps/download-wallpapers.py 
:: Downloading Google Maps wallpapers.
1003
1004
1006
Traceback (most recent call last):
  File "maps/download-wallpapers.py", line 100, in <module>
    download_wallpapers()
  File "maps/download-wallpapers.py", line 41, in download_wallpapers
    wallpaper_info = get_wallpaper_info(wallpaper_id)
  File "maps/download-wallpapers.py", line 74, in get_wallpaper_info
    return json.load(urllib2.urlopen(wallpaper_info_url))["dataUri"]
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I tried kzvdar42's [fork](https://github.com/kzvdar42/google-wallpaper-downloaders), and got this:
```
user@computer: google-wallpaper-downloaders$ python maps/download-wallpapers.py
Traceback (most recent call last):
  File "maps/download-wallpapers.py", line 29, in <module>
    write = tqdm.write
AttributeError: module 'tqdm' has no attribute 'write'
```

**Comment by kylrth** [comment]
The `tqdm` version I have is `4.36.1`.

**Comment by kzvdar42** [comment]
Fixed the error in my fork. (changed `import tqdm` to `from tqdm import tqdm`)😅

Next time, please, mention me for faster response (as now I've seen this only by accident)
